<?xml version="1.0"?>
<package format="2">
    <name>pose_to_tf</name>
    <version>0.0.1</version>
    <description>Utility package to convert pose messages to TF transforms.</description>

    <maintainer email="sugerdzn@gmail.com">Tim Seeger</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <build_depend>roscpp</build_depend>
    <build_depend>tf2_ros</build_depend>
    <build_depend>geometry_msgs</build_depend>

    <exec_depend>roscpp</exec_depend>
    <exec_depend>tf2_ros</exec_depend>
    <exec_depend>geometry_msgs</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>