contestants:
- inter_planner: empty
  local_planner: crowdnav
  name: crowdnav_empty
- inter_planner: empty
  local_planner: drlvo
  name: drlvo_empty
- inter_planner: empty
  local_planner: dwb
  name: dwb_empty
- inter_planner: empty
  local_planner: graceful
  name: graceful_empty
- inter_planner: empty
  local_planner: mppi
  name: mppi_empty
- inter_planner: empty
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_empty
- inter_planner: empty
  local_planner: rotation_shim
  name: rotation_shim_empty
- inter_planner: follow_point
  local_planner: crowdnav
  name: crowdnav_follow_point
- inter_planner: follow_point
  local_planner: drlvo
  name: drlvo_follow_point
- inter_planner: follow_point
  local_planner: dwb
  name: dwb_follow_point
- inter_planner: follow_point
  local_planner: graceful
  name: graceful_follow_point
- inter_planner: follow_point
  local_planner: mppi
  name: mppi_follow_point
- inter_planner: follow_point
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_follow_point
- inter_planner: follow_point
  local_planner: rotation_shim
  name: rotation_shim_follow_point
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid
  local_planner: crowdnav
  name: crowdnav_nav_to_pose_replan
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid
  local_planner: drlvo
  name: drlvo_nav_to_pose_replan
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid
  local_planner: dwb
  name: dwb_nav_to_pose_replan
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid 
  local_planner: graceful
  name: graceful_nav_to_pose_replan
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid
  local_planner: mppi
  name: mppi_nav_to_pose_replan
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid 
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_nav_to_pose_replan
- inter_planner: nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid
  local_planner: rotation_shim
  name: rotation_shim_nav_to_pose_replan
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: crowdnav
  name: crowdnav_navigate_through_replan_recovery
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: drlvo
  name: drlvo_navigate_through_replan_recovery
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: dwb
  name: dwb_navigate_through_replan_recovery
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: graceful
  name: graceful_navigate_through_replan_recovery
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: mppi
  name: mppi_navigate_through_replan_recovery
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_through_replan_recovery
- inter_planner: navigate_through_poses_w_replanning_and_recovery
  local_planner: rotation_shim
  name: rotation_shim_navigate_through_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: crowdnav
  name: crowdnav_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: drlvo
  name: drlvo_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: dwb
  name: dwb_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: graceful
  name: graceful_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: mppi
  name: mppi_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_and_recovery
  local_planner: rotation_shim
  name: rotation_shim_navigate_to_replan_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: crowdnav
  name: crowdnav_navigate_to_replan_patience_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: drlvo
  name: drlvo_navigate_to_replan_patience_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: dwb
  name: dwb_navigate_to_replan_patience_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: graceful
  name: graceful_navigate_to_replan_patience_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: mppi
  name: mppi_navigate_to_replan_patience_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_to_replan_patience_recovery
- inter_planner: navigate_to_pose_w_replanning_goal_patience_and_recovery
  local_planner: rotation_shim
  name: rotation_shim_navigate_to_replan_patience_recovery
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: crowdnav
  name: crowdnav_navigate_replan_recovery_valid
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: drlvo
  name: drlvo_navigate_replan_recovery_valid
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: dwb
  name: dwb_navigate_replan_recovery_valid
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: graceful
  name: graceful_navigate_replan_recovery_valid
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: mppi
  name: mppi_navigate_replan_recovery_valid
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_replan_recovery_valid
- inter_planner: navigate_w_recovery_and_replanning_only_if_path_becomes_invalid
  local_planner: rotation_shim
  name: rotation_shim_navigate_replan_recovery_valid
- inter_planner: navigate_w_replanning_distance
  local_planner: crowdnav
  name: crowdnav_navigate_replan_distance
- inter_planner: navigate_w_replanning_distance
  local_planner: drlvo
  name: drlvo_navigate_replan_distance
- inter_planner: navigate_w_replanning_distance
  local_planner: dwb
  name: dwb_navigate_replan_distance
- inter_planner: navigate_w_replanning_distance
  local_planner: graceful
  name: graceful_navigate_replan_distance
- inter_planner: navigate_w_replanning_distance
  local_planner: mppi
  name: mppi_navigate_replan_distance
- inter_planner: navigate_w_replanning_distance
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_replan_distance
- inter_planner: navigate_w_replanning_distance
  local_planner: rotation_shim
  name: rotation_shim_navigate_replan_distance
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: crowdnav
  name: crowdnav_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: drlvo
  name: drlvo_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: dwb
  name: dwb_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: graceful
  name: graceful_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: mppi
  name: mppi_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_goal_is_updated
  local_planner: rotation_shim
  name: rotation_shim_navigate_replan_goal_updated
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: crowdnav
  name: crowdnav_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: drlvo
  name: drlvo_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: dwb
  name: dwb_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: graceful
  name: graceful_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: mppi
  name: mppi_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_only_if_path_becomes_invalid
  local_planner: rotation_shim
  name: rotation_shim_navigate_replan_path_invalid
- inter_planner: navigate_w_replanning_speed
  local_planner: crowdnav
  name: crowdnav_navigate_replan_speed
- inter_planner: navigate_w_replanning_speed
  local_planner: drlvo
  name: drlvo_navigate_replan_speed
- inter_planner: navigate_w_replanning_speed
  local_planner: dwb
  name: dwb_navigate_replan_speed
- inter_planner: navigate_w_replanning_speed  
  local_planner: graceful
  name: graceful_navigate_replan_speed
- inter_planner: navigate_w_replanning_speed  
  local_planner: mppi
  name: mppi_navigate_replan_speed
- inter_planner: navigate_w_replanning_speed
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_replan_speed
- inter_planner: navigate_w_replanning_speed
  local_planner: rotation_shim
  name: rotation_shim_navigate_replan_speed
- inter_planner: navigate_w_replanning_time
  local_planner: crowdnav
  name: crowdnav_navigate_replan_time
- inter_planner: navigate_w_replanning_time
  local_planner: drlvo
  name: drlvo_navigate_replan_time
- inter_planner: navigate_w_replanning_time
  local_planner: dwb
  name: dwb_navigate_replan_time
- inter_planner: navigate_w_replanning_time
  local_planner: graceful
  name: graceful_navigate_replan_time
- inter_planner: navigate_w_replanning_time
  local_planner: mppi
  name: mppi_navigate_replan_time
- inter_planner: navigate_w_replanning_time
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_navigate_replan_time
- inter_planner: navigate_w_replanning_time
  local_planner: rotation_shim
  name: rotation_shim_navigate_replan_time
- inter_planner: odometry_calibration
  local_planner: crowdnav
  name: crowdnav_odometry_calibration
- inter_planner: odometry_calibration
  local_planner: drlvo
  name: drlvo_odometry_calibration
- inter_planner: odometry_calibration
  local_planner: dwb
  name: dwb_odometry_calibration
- inter_planner: odometry_calibration
  local_planner: graceful
  name: graceful_odometry_calibration
- inter_planner: odometry_calibration
  local_planner: mppi
  name: mppi_odometry_calibration
- inter_planner: odometry_calibration
  local_planner: regulated_pure_pursuit
  name: regulated_pure_pursuit_odometry_calibration
- inter_planner: odometry_calibration
  local_planner: rotation_shim
  name: rotation_shim_odometry_calibration
